title: Hannah's Homepage
page-top-title: Hannah Guan
top-section-bg-text: Ruijia (Hannah) Guan
about-subtitle: ABOUT
education-subtitle: EDUCATION
experience-subtitle: EXPERIENCE
publications-subtitle: PUBLICATIONS
news-subtitle: NEWS
awards-subtitle: HONORS & AWARDS
teaching-subtitle: TEACHING & SERVICE
miscellaneous-subtitle: MISCELLANEOUS
